name: Run Playwright Tests Only on Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-on-main:
    name: Run Playwright tests on main branch
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Run tests on main
        run: mvn clean test
